apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: wordpress
spec:
  containers:
  - name: wordpress-pod
    image: wordpress/4.9.2-php5.6-apache
    ports:
    - containerPort: 8090
